/**
 * Chat-related type definitions for the conversational UI
 */

/** Message role types */
export type MessageRole = 'user' | 'assistant' | 'system';

/** Expert agent reference in a message */
export interface MessageExpert {
  id: string;
  name: string;
  avatar?: string;
  role?: string;
}

/** Inline component embedded in a message */
export interface InlineComponent {
  type: 'chart' | 'map' | 'table' | 'approval' | 'alert' | 'document' | 'task' | 'image';
  data: unknown;
  title?: string;
}

/** Artifact reference attached to a message */
export interface MessageArtifactRef {
  artifactId: string;
  name: string;
  type: 'document' | 'chart' | 'map' | 'table' | 'image' | 'video';
  previewUrl?: string;
}

/** A single chat message */
export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  expert?: MessageExpert;
  timestamp: string;
  artifacts?: MessageArtifactRef[];
  components?: InlineComponent[];
  thinking?: string;
  hallucinationRisk?: number;
  toolsUsed?: string[];
  /** Files attached to this message (uploaded by user or generated by AI) */
  files?: SessionFile[];
  /** For streaming: whether this message is still being generated */
  isStreaming?: boolean;
  /** For streaming: partial content being built */
  streamContent?: string;
}

/** File record attached to a session or message */
export interface SessionFile {
  id: string;
  name: string;
  type: 'uploaded' | 'generated';
  path?: string;
  size?: number;
  mimeType?: string;
  createdAt: string;
  messageId?: string;  // which message generated/uploaded this
}

/** Expert change audit log entry */
export interface ChangeLogEntry {
  id: string;
  timestamp: string;
  agentId: string;
  agentName: string;
  changeType: 'memory_added' | 'memory_updated' | 'memory_deleted' |
               'setting_changed' | 'skill_added' | 'skill_removed' |
               'diary_added' | 'conclusion_generated';
  description: string;
  before?: string;
  after?: string;
}

/** Chat session metadata */
export interface ChatSession {
  id: string;
  title: string;
  expertId?: string;
  expertName?: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
  workspaceId?: string;
  /** AI-generated conversation conclusion */
  conclusion?: string;
  conclusionGeneratedAt?: string;
  /** Files uploaded or generated in this session */
  files?: SessionFile[];
  /** Expert change log entries for this session */
  changeLog?: ChangeLogEntry[];
  /** User-defined tags for categorization */
  tags?: string[];
}

/** WebSocket streaming chunk */
export interface StreamChunk {
  type: 'chunk' | 'done' | 'error' | 'component' | 'artifact';
  sessionId: string;
  messageId: string;
  content?: string;
  component?: InlineComponent;
  artifact?: MessageArtifactRef;
  error?: string;
  thinking?: string;
  toolsUsed?: string[];
  hallucinationRisk?: number;
}

/** Chat API request payload */
export interface SendMessageRequest {
  session_id: string;
  message: string;
  expert_id?: string;
  attachments?: string[];
}

/** Chat API response */
export interface SendMessageResponse {
  message_id: string;
  session_id: string;
  content: string;
  expert?: MessageExpert;
  artifacts?: MessageArtifactRef[];
  components?: InlineComponent[];
  thinking?: string;
  tools_used?: string[];
  hallucination_risk?: number;
}

/** Session creation request */
export interface CreateSessionRequest {
  title?: string;
  expert_id?: string;
  workspace_id?: string;
}

/** Session creation response */
export interface CreateSessionResponse {
  session: ChatSession;
}

/** Sessions list response */
export interface SessionsListResponse {
  sessions: ChatSession[];
  total: number;
}

/** Messages list response */
export interface MessagesListResponse {
  messages: ChatMessage[];
  total: number;
}
